[tool.ruff]
# Enable Pycodestyle (`E`), Pyflakes (`F`), Pyupgrade (`UP`), flake8-commas (`COM`) and flake8-django (`DJ`) codes
select = ["E", "F", "UP", "COM", "DJ"]
ignore = []

# Allow autofix for all enabled rules (when `--fix`) is provided.
fixable = ["A", "B", "C", "D", "E", "F", "G", "I", "N", "Q", "S", "T", "W", "ANN", "ARG", "BLE", "COM", "DJ", "DTZ", "EM", "ERA", "EXE", "FBT", "ICN", "INP", "ISC", "NPY", "PD", "PGH", "PIE", "PL", "PT", "PTH", "PYI", "RET", "RSE", "RUF", "SIM", "SLF", "TCH", "TID", "TRY", "UP", "YTT"]
unfixable = []

# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
]
per-file-ignores = {}

# Set max line length
line-length = 100

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

# Assume Python 3.10.
target-version = "py310"

[tool.ruff.mccabe]
# Set complexity level of 8
max-complexity = 8

[tool.pytest.ini_options]
filterwarnings = [
    # Hide Deprecation Warnings
    "ignore::DeprecationWarning",
]

markers = [
  "email_configured: these tests require MAIL_SERVER, MAIL_USERNAME, MAIL_PASSWORD, MAIL_PORT, MAIL_USE_TLS, MAIL_USE_SSL to be set in a .env file",
  "oauth_configured: these tests require client_secret.json to be put in source directory (next to app.py)",
]
